alyssa = User.create!(name: "Alyssa", username: "alyssa", email: "alyssa.email", password: "123456")
matt = User.create!(name: "Matt", username: "matt", email: "matt.email", password: "123456")
duke = User.create!(name: "Duke", username: "duke", email: "duke.email", password: "123456")

EmpanadaType.create(name: "Beef")
EmpanadaType.create(name: "Malbec Beef")
EmpanadaType.create(name: "Spinach")
EmpanadaType.create(name: "Corn")
EmpanadaType.create(name: "Nutella")

order_one = Order.create(eater: alyssa)
order_one.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_one.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_one.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))

order_two = Order.create(eater: duke)
order_two.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_two.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_two.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))

order_three = Order.create(eater: matt)
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
order_three.empanadas << Empanada.create(empanada_type_id: (rand(5) + 1))
